# Nixpacks configuration for Node.js version
[variables]
NODE_VERSION = "20.17.0"
HOST = "0.0.0.0"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm install"

[phases.build]
cmd = "npm run build"

[start]
# Run Astro hybrid build with Node.js server (supports API endpoints)
cmd = "node dist/server/entry.mjs"