# Nixpacks configuration for Node.js version
[variables]
NODE_VERSION = "20.17.0"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npx serve dist -p 3000"